import {formulations} from '../domain/formulations.js';
import {createGame,act,nextMission} from '../domain/game-engine.js';
import {THREE,createWorld,box,ball,tube,label,person,safeStorage,saveReport} from './scene-kit.js';
const $=id=>document.getElementById(id);let state=createGame(),paused=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const stored=safeStorage('pharma-v2-completed');let completed=new Set((Array.isArray(stored)?stored:[]).filter(x=>formulations.some(m=>m.id===x)));
let world,avatar,pestle,solution,unknown,particles=[],rayTargets=[];
$('boundary').textContent='Educational prototype for nonsterile extemporaneous dispensing. Holograms symbolize verified materials; they are not molecular synthesis. No doses or real recipes are provided. Requires pharmacist and curriculum review before formal training use.';
$('scene-note').textContent='Use the decision buttons below. Material holograms are symbolic. Full gameplay works offline.';
function render(){const m=formulations[state.mission],step=m.steps[state.step];document.body.classList.toggle('failed',state.status==='failed');$('edition').textContent=`Learning campaign / ${String(state.mission+1).padStart(2,'0')}`;$('title').textContent=m.name;$('brief').textContent=m.brief;$('chapter').textContent=m.medicine;$('progress').max=m.steps.length;$('progress').value=state.step;$('score').textContent=state.score;$('saved').textContent=`${completed.size} / ${formulations.length}`;$('card').replaceChildren();const para=document.createElement('p');para.textContent=m.card;$('card').append(para);const ol=document.createElement('ol');for(const s of m.steps){const li=document.createElement('li');li.textContent=s.title;ol.append(li)}$('card').append(ol);$('objective').textContent=state.status==='complete'?'Mission complete':state.status==='failed'?'Review and try again':step.title;$('feedback').textContent=paused?'Game paused. Resume when you are ready.':state.feedback;$('status').textContent=paused?'Paused':state.status==='playing'?`Decision ${state.step+1} / ${m.steps.length}`:state.status;$('actions').replaceChildren();if(state.status==='playing')for(const [id,title] of step.choices){const b=document.createElement('button');b.textContent=title;b.disabled=paused;b.onclick=()=>choose(id);$('actions').append(b)}$('next').hidden=state.status!=='complete';$('next').textContent=state.mission===2?'Replay the campaign →':'Enter the next chamber →';$('next').disabled=paused;$('journal').replaceChildren();for(const item of state.journal){const li=document.createElement('li');li.textContent=`${item.correct?'✓':'↺'} ${item.lesson}`;$('journal').append(li)}$('motion').setAttribute('aria-pressed',String(reduced));$('motion').textContent=reduced?'Motion reduced':'Reduce motion';if(unknown)unknown.visible=state.step<3;if(solution)solution.material.color.set(state.status==='failed'?0xb56479:state.status==='complete'?0x91e2ab:0x68cbd4);}
function choose(id){if(paused)return;state=act(state,id);if(state.status==='complete'){completed.add(formulations[state.mission].id);safeStorage('pharma-v2-completed',[...completed]);}render();}
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';render()};$('motion').onclick=()=>{reduced=!reduced;render()};$('retry').onclick=()=>{state=createGame(state.mission);render()};$('next').onclick=()=>{state=nextMission(state);render()};$('export').onclick=()=>saveReport('pharma-attempt.json',{game:'Pharma Simulation',version:'0.2.0',case:formulations[state.mission].id,...state});render();
try{world=createWorld($('world'));const {scene}=world;
 box(scene,0,-.2,0,13,.4,10,0x163c44);box(scene,0,2,-4.7,13,4,.25,0x174954);box(scene,-6.35,1.5,0,.25,3,9.5,0x10303b);
 for(let x=-5;x<6;x+=2)box(scene,x,.015,0,.02,.02,9,0x326069);for(let z=-4;z<5;z+=2)box(scene,0,.016,z,12,.02,.02,0x326069);
 box(scene,0,1.12,0,6,.23,2.3,0xd5e4de);box(scene,-2,0.55,0,1.3,1.1,1.9,0x335862);box(scene,2,.55,0,1.3,1.1,1.9,0x335862);
 tube(scene,-1.5,1.5,0,.65,.4,.45,0xc9d8d1);pestle=tube(scene,-1.48,1.95,0,.13,.2,.85,0xd8e4d8);pestle.rotation.z=.6;label(scene,'Preparation bench',0,2.85,1,3.5);
 tube(scene,1.1,1.65,0,.5,.5,.95,0xb4e8f1,true);solution=tube(scene,1.1,1.43,0,.45,.45,.48,0x68cbd4);
 box(scene,4,1.5,-3,3,.15,1,0x7eaaa7);box(scene,4,.65,-3,3,.15,1,0x7eaaa7);for(let i=0;i<5;i++){tube(scene,2.9+i*.55,1.9,-3,.18,.2,.65,i%2?0xbb8950:0x609c89);box(scene,2.9+i*.55,2.25,-3,.21,.15,.21,0x132b2e);}label(scene,'Verified inventory',4,2.9,-3,3);
 const colors=[0x8ef2c5,0x7fb3ff,0xf4d687,0xef839a];for(let i=0;i<4;i++){const g=new THREE.Group();g.position.set(-4.5+i*2.4,3.4,-2);for(let j=0;j<3;j++){ball(g,(j-1)*.28,Math.sin(j*2)*.18,0,.19,colors[i]);if(j<2){const bond=box(g,(j-.5)*.28,0,0,.28,.06,.06,0xb3ccd1);bond.rotation.z=.2;}}scene.add(g);label(g,['Active','Medium','Vehicle','UNKNOWN'][i],0,.6,0,1.8,i===3?'#ffb4bd':'#d6fff2');particles.push(g);if(i===3)unknown=g;}
 box(scene,-4.5,.75,2.5,1.4,1.5,1.2,0x477976);box(scene,-4.5,1.58,2.5,1.6,.18,1.4,0xadd5c5);label(scene,'Independent check',-4.4,2.65,2.5,2.7);
 avatar=person(scene,4,2.5,0xa8d3d4);label(scene,'Virtual patient',4,2.55,2.5,2.5);label(scene,'PHARMWEB3  /  DISPENSING LAB',0,4.5,-4.5,6);
}catch(e){$('fallback').hidden=false;console.warn('WebGL unavailable; accessible gameplay remains active.',e.message)}render();
let last=performance.now(),elapsed=0;function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!paused&&!reduced)elapsed+=dt;if(world){if(!paused){for(let i=0;i<particles.length;i++){particles[i].position.y=3.4+(reduced?0:Math.sin(elapsed+i)*.14);particles[i].rotation.y=reduced?0:elapsed*.2;}if(avatar){const target=state.status==='failed'?-1.12:0;avatar.group.rotation.z+=(target-avatar.group.rotation.z)*(reduced?1:Math.min(1,dt*4));}if(pestle)pestle.rotation.z=.6+(!reduced&&state.step>3&&state.step<7?Math.sin(elapsed*3)*.2:0);}world.renderer.render(world.scene,world.camera)}requestAnimationFrame(frame)}requestAnimationFrame(frame);
